### ISSUE TITLE
[vector-annotator] TypeError: log() got an unexpected keyword argument 'api_url'

### ISSUE THREAD

**Issue by dvsrepo** [argilla-io/argilla-streamlit#10]
When selecting a set of data points and click Annotate: 

<img width="1224" alt="Screenshot 2023-02-28 at 16 51 01" src="https://user-images.githubusercontent.com/1107111/221906005-03aa443b-4374-49e2-a5b4-fc7e370ce32c.png">

**Comment by davidberenstein1957** [comment]
forgot to reference the issue within my commit but it was resolved
